chr_config: support non-jumbo builds
Additionally "blacklists" blink's svg
core module in jumbo builds, since it was leading
to the following compilation error:

In file included from gen/third_party/blink/renderer/core/svg/svg_jumbo_2.cc:42:
In file included from ./../../../third_party/blink/renderer/core/svg/svg_foreign_object_element.cc:25:
In file included from ../../../third_party/blink/renderer/core/layout/svg/layout_svg_foreign_object.h:24:
In file included from ../../../third_party/blink/renderer/core/layout/svg/layout_svg_block.h:23:
In file included from ../../../third_party/blink/renderer/core/layout/layout_block_flow.h:44:
In file included from ../../../third_party/blink/renderer/core/layout/layout_block.h:29:
In file included from ../../../third_party/blink/renderer/core/layout/layout_box.h:30:
In file included from ../../../third_party/blink/renderer/core/layout/custom/custom_layout_child.h:8:
In file included from ../../../third_party/blink/renderer/core/css/cssom/prepopulated_computed_style_property_map.h:9:
../../../third_party/blink/renderer/core/css/css_property_id_templates.h:18:8: error: explicit specialization of 'WTF::HashTraits<blink::CSSPropertyID>' after instantiation
struct HashTraits<blink::CSSPropertyID>
       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../../../third_party/blink/renderer/platform/wtf/hash_map.h:71:20: note: implicit instantiation first required here
  typedef typename MappedTraits::TraitType MappedType;
                   ^
1 error generated.

Signed-off-by: Nick Diego Yamane <nick@diegoyam.com>